In [ ]:
import pandas as pd
dados = {
    "nome": ["João", "Carlos", "Maria", "Ana", "Pedro"],
    "idade": [25, 30, 22, 28, 35],
    "Naturalidade": ["SP", "RJ", "MG", "RS", "BA"]
}

df = pd.DataFrame(dados)
print(df)

     nome  idade Naturalidade
0    João     25           SP
1  Carlos     30           RJ
2   Maria     22           MG
3     Ana     28           RS
4   Pedro     35           BA

In [ ]:
#verificar coluna especifica
print (df["idade"])

0    25
1    30
2    22
3    28
4    35
Name: idade, dtype: int64

In [ ]:
#puxar valor condicional

print(df["idade"]>30)

0    False
1    False
2    False
3    False
4     True
Name: idade, dtype: bool

In [ ]:
#puxar valor conditional com informacoes completas
# 1 filtrar idade - df["idade"]>30
# 2 puxar todas as infos - df[]
print(df[df["idade"]<30])

    nome  idade Naturalidade
0   João     25           SP
2  Maria     22           MG
3    Ana     28           RS

In [ ]:
# puxar registros de um unico nome

#traz informacoes vazias, indicando apenas atrves do indice quem é verdadeiro para a declaracao =='Ana'
#print(df['nome']=='Ana')
print(df[df['nome']=='Ana')]

SyntaxError: closing parenthesis ')' does not match opening parenthesis '[' (44430868.py, line 5)

In [ ]:
#estatistica descritiva
df.describe()

           idade
count   5.000000
mean   28.000000
std     4.949747
min    22.000000
25%    25.000000
50%    28.000000
75%    30.000000
max    35.000000

In [ ]:
#filtro de primeiras linhas
df.head(2)

     nome  idade Naturalidade
0    João     25           SP
1  Carlos     30           RJ

In [ ]:
#aplicar uma funcao para calcular idade + 2
df['idade2'] = df['idade'].apply(lambda x: x+2) ## ao usar lambda, cada valor (x) da coluna 'idade' recebe a soma de + 2

print(df)

     nome  idade Naturalidade  idade2
0    João     25           SP      27
1  Carlos     30           RJ      32
2   Maria     22           MG      24
3     Ana     28           RS      30
4   Pedro     35           BA      37

In [ ]:
# contagem de valor
df['Naturalidade'].value_counts() #retorna a quantidade em que a naturalidade aparece na variavel df

Naturalidade
SP    1
RJ    1
MG    1
RS    1
BA    1
Name: count, dtype: int64

In [ ]:
#ordenar dados
#asscending = true (ordem crescente)
#ascending = false (ordem descrescente)

df.sort_values("Naturalidade", ascending=False) #ordenar por naturalidade

     nome  idade Naturalidade  idade2
0    João     25           SP      27
3     Ana     28           RS      30
1  Carlos     30           RJ      32
2   Maria     22           MG      24
4   Pedro     35           BA      37

In [ ]:
#agrupar por (groupby) / calculo de media de idade por naturalidade
media_nat = df.groupby("Naturalidade")["idade"].mean()
print(media_nat)

Naturalidade
BA    35.0
MG    22.0
RJ    30.0
RS    28.0
SP    25.0
Name: idade, dtype: float64